import { AxiosError } from 'axios';
import { useQuery } from 'react-query';

import { axios } from '../config/axiosConfig';

const val = {
  genderByGrades: [
    {
      row: 'female',
      _total_female: 7,
      _1_female: 2,
      _2_female: 2,
      _3_female: 1,
      _4_female: 2,
      _5_female: 0,
      _6_female: 0,
      _7_female: 0,
    },
    {
      row: 'male',
      _total_male: 6,
      _1_male: 2,
      _2_male: 1,
      _3_male: 2,
      _4_male: 1,
      _5_male: 0,
      _6_male: 0,
      _7_male: 0,
    },
    {
      row: 'total',
      _total_total: 13,
      _1_total: 4,
      _2_total: 3,
      _3_total: 3,
      _4_total: 3,
      _5_total: 0,
      _6_total: 0,
      _7_total: 0,
    },
  ],
  foodServiceByGenders: [
    {
      female: 4,
      male: 5,
      total: 9,
      row: 'copa_de_leche',
    },
    {
      female: 5,
      male: 4,
      total: 9,
      row: 'almuerzo',
    },
  ],
  repeatersByGender: [
    {
      row: 'total',
      _1_total_female: 2,
      _1_total_male: 1,
      _1_total_total: 3,
      _2_total_female: 2,
      _2_total_male: 0,
      _2_total_total: 2,
      _4_total_female: 1,
      _4_total_male: 1,
      _4_total_total: 2,
      _3_total_female: 0,
      _3_total_male: 1,
      _3_total_total: 1,
      _6_total_female: 0,
      _6_total_male: 0,
      _6_total_total: 0,
      _7_total_female: 0,
      _7_total_male: 0,
      _7_total_total: 0,
      _5_total_female: 0,
      _5_total_male: 0,
      _5_total_total: 0,
    },
    {
      row: 'first',
      _1_female: 1,
      _1_male: 1,
      _1_total: 2,
      _2_female: 2,
      _2_male: 0,
      _2_total: 2,
      _4_female: 1,
      _4_male: 1,
      _4_total: 2,
      _3_female: 0,
      _3_male: 1,
      _3_total: 1,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'second',
      _1_female: 1,
      _1_male: 0,
      _1_total: 1,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'third',
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'forth',
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
  ],
  studentsByAgeAndGender: [
    {
      row: 'five',
      _total_female: 0,
      _total_male: 1,
      _total_total: 1,
      _1_female: 0,
      _1_male: 1,
      _1_total: 1,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'six',
      _total_female: 0,
      _total_male: 0,
      _total_total: 0,
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'seven',
      _total_female: 3,
      _total_male: 2,
      _total_total: 5,
      _1_female: 1,
      _1_male: 0,
      _1_total: 1,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 2,
      _4_male: 1,
      _4_total: 3,
      _3_female: 0,
      _3_male: 1,
      _3_total: 1,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'eight',
      _total_female: 2,
      _total_male: 1,
      _total_total: 3,
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 1,
      _2_male: 0,
      _2_total: 1,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 1,
      _3_male: 1,
      _3_total: 2,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'nine',
      _total_female: 2,
      _total_male: 2,
      _total_total: 4,
      _1_female: 1,
      _1_male: 1,
      _1_total: 2,
      _2_female: 1,
      _2_male: 1,
      _2_total: 2,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'ten',
      _total_female: 0,
      _total_male: 0,
      _total_total: 0,
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'eleven',
      _total_female: 0,
      _total_male: 0,
      _total_total: 0,
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'twelve',
      _total_female: 0,
      _total_male: 0,
      _total_total: 0,
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'thirteen',
      _total_female: 0,
      _total_male: 0,
      _total_total: 0,
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'fourteen',
      _total_female: 0,
      _total_male: 0,
      _total_total: 0,
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'fifteen',
      _total_female: 0,
      _total_male: 0,
      _total_total: 0,
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'sixteen',
      _total_female: 0,
      _total_male: 0,
      _total_total: 0,
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'seventeen',
      _total_female: 0,
      _total_male: 0,
      _total_total: 0,
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
    {
      row: 'eighteen',
      _total_female: 0,
      _total_male: 0,
      _total_total: 0,
      _1_female: 0,
      _1_male: 0,
      _1_total: 0,
      _2_female: 0,
      _2_male: 0,
      _2_total: 0,
      _4_female: 0,
      _4_male: 0,
      _4_total: 0,
      _3_female: 0,
      _3_male: 0,
      _3_total: 0,
      _6_female: 0,
      _6_male: 0,
      _6_total: 0,
      _7_female: 0,
      _7_male: 0,
      _7_total: 0,
      _5_female: 0,
      _5_male: 0,
      _5_total: 0,
    },
  ],
  studentsByCountryAndGender: [
    {
      row: 'alemania',
      _total_female: 0,
      _total_male: 1,
      _total_total: 1,
      _4_female: 0,
      _4_male: 1,
      _4_total: 1,
    },
    {
      row: 'argentina',
      _total_female: 4,
      _total_male: 4,
      _total_total: 8,
      _1_female: 2,
      _1_male: 2,
      _1_total: 4,
      _2_female: 2,
      _2_male: 0,
      _2_total: 2,
      _3_female: 0,
      _3_male: 2,
      _3_total: 2,
    },
    {
      row: 'españa',
      _total_female: 1,
      _total_male: 0,
      _total_total: 1,
      _4_female: 1,
      _4_male: 0,
      _4_total: 1,
    },
    {
      row: 'francia',
      _total_female: 1,
      _total_male: 1,
      _total_total: 2,
      _2_female: 0,
      _2_male: 1,
      _2_total: 1,
      _3_female: 1,
      _3_male: 0,
      _3_total: 1,
    },
    {
      row: 'italia',
      _total_female: 1,
      _total_male: 0,
      _total_total: 1,
      _4_female: 1,
      _4_male: 0,
      _4_total: 1,
    },
  ],
};

type QueryResult = {
  genderByGrades: any[];
  foodServiceByGenders: any[];
  repeatersByGender: any[];
  studentsByAgeAndGender: any[];
  studentsByCountryAndGender: any[];
};

const getAnnuallyReport = async (type: 'initial' | 'final') => {
  const response = await axios.get(`/reports/annually/${type}`);
  console.log({ getAnnuallyReport: response.data });
  // return response.data;
  return val;
};

export const useAnnuallyReport = (type: 'initial' | 'final') => {
  return useQuery<QueryResult, AxiosError>(['report_annually', type], () => getAnnuallyReport(type), {
    staleTime: Infinity,
    cacheTime: Infinity,
    refetchOnWindowFocus: false,
    onError: (error) => console.log('getAnnuallyReport - error ->', error),
  });
};
